// When included from build.rs via `#[path]`, `super` refers to the
// build script root where `schema` is also included via `#[path]`.
// When compiled as part of the library crate, `super` is the crate root
// where `schema` is a sibling module.
use super::schema::{MetricType, MetricsSchema, TagValueType};

use std::fmt::Write;
use std::path::Path;

/// Generate Rust source code from a metrics JSON schema file.
///
/// This function is intended to be called from a `build.rs` script. It reads
/// the JSON file at `schema_path`, validates it, generates type-safe Rust code,
/// and writes the output to `$OUT_DIR/metrics_generated.rs`.
///
/// # Usage in `build.rs`
///
/// ```rust,ignore
/// fn main() {
///     chalk_metrics::codegen::generate("metrics.json");
/// }
/// ```
///
/// Then in your library code:
///
/// ```rust,ignore
/// mod metrics {
///     include!(concat!(env!("OUT_DIR"), "/metrics_generated.rs"));
/// }
/// ```
///
/// # Panics
///
/// Panics if the schema file cannot be read, parsed, or fails validation.
pub fn generate(schema_path: impl AsRef<Path>) {
    let schema_path = schema_path.as_ref();
    let json = std::fs::read_to_string(schema_path).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to read schema file '{}': {e}",
            schema_path.display()
        )
    });

    let schema = MetricsSchema::from_json(&json).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to parse schema '{}': {e}",
            schema_path.display()
        )
    });

    schema.validate().unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: schema validation failed for '{}':\n{e}",
            schema_path.display()
        )
    });

    let code = generate_code(&schema);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set (must be run from build.rs)");
    let out_path = Path::new(&out_dir).join("metrics_generated.rs");
    std::fs::write(&out_path, code).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to write '{}': {e}",
            out_path.display()
        )
    });

    // Re-run build script if the schema file changes.
    println!("cargo:rerun-if-changed={}", schema_path.display());
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let mut out = c.to_uppercase().to_string();
                    out.extend(chars);
                    out
                }
            }
        })
        .collect()
}

/// Build a PascalCase variant name from namespace path + metric name.
/// e.g., ["http", "auth"] + "login_latency" -> "HttpAuthLoginLatency"
fn variant_name(namespace: &[String], metric_name: &str) -> String {
    let mut name = String::new();
    for ns in namespace {
        name.push_str(&to_pascal_case(ns));
    }
    name.push_str(&to_pascal_case(metric_name));
    name
}

fn generate_code(schema: &MetricsSchema) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "// Generated by chalk-metrics codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use std::fmt;").unwrap();
    writeln!(out, "use std::hash::{{Hash, Hasher}};").unwrap();
    writeln!(out).unwrap();

    generate_metric_type_reexport(&mut out);
    generate_tag_types(&mut out, schema);
    generate_metric_id(&mut out, schema);
    generate_metric_tags_structs(&mut out, schema);

    out
}

fn generate_metric_type_reexport(out: &mut String) {
    writeln!(out, "/// The aggregation type for a metric.").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub enum MetricType {{").unwrap();
    writeln!(out, "    Count,").unwrap();
    writeln!(out, "    Gauge,").unwrap();
    writeln!(out, "    Histogram,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn generate_tag_types(out: &mut String, schema: &MetricsSchema) {
    let mut tag_names: Vec<&String> = schema.tags.keys().collect();
    tag_names.sort();

    for tag_name in &tag_names {
        let tag_def = &schema.tags[*tag_name];
        let type_name = to_pascal_case(tag_name);

        match tag_def.value_type {
            TagValueType::Enum => {
                let values = tag_def.values.as_ref().unwrap();
                writeln!(out, "/// Tag values for `{tag_name}` (exported as `{}`).", tag_def.export_name).unwrap();
                writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
                writeln!(out, "pub enum {type_name} {{").unwrap();
                for value in values {
                    writeln!(out, "    {},", to_pascal_case(value)).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl {type_name} {{").unwrap();
                writeln!(out, "    /// Returns the string representation of this tag value.").unwrap();
                writeln!(out, "    pub fn as_str(&self) -> &'static str {{").unwrap();
                writeln!(out, "        match self {{").unwrap();
                for value in values {
                    writeln!(out, "            {type_name}::{} => \"{value}\",", to_pascal_case(value)).unwrap();
                }
                writeln!(out, "        }}").unwrap();
                writeln!(out, "    }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl fmt::Display for {type_name} {{").unwrap();
                writeln!(out, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{").unwrap();
                writeln!(out, "        f.write_str(self.as_str())").unwrap();
                writeln!(out, "    }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
            TagValueType::String => {
                writeln!(out, "/// Tag values for `{tag_name}` (exported as `{}`). Accepts arbitrary strings.", tag_def.export_name).unwrap();
                writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq, Hash)]").unwrap();
                writeln!(out, "pub struct {type_name}(pub String);").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl {type_name} {{").unwrap();
                writeln!(out, "    pub fn as_str(&self) -> &str {{ &self.0 }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl fmt::Display for {type_name} {{").unwrap();
                writeln!(out, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{ f.write_str(&self.0) }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl From<&str> for {type_name} {{").unwrap();
                writeln!(out, "    fn from(s: &str) -> Self {{ {type_name}(s.to_owned()) }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl From<String> for {type_name} {{").unwrap();
                writeln!(out, "    fn from(s: String) -> Self {{ {type_name}(s) }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }
}

fn generate_metric_id(out: &mut String, schema: &MetricsSchema) {
    let flat = schema.flatten_metrics();

    writeln!(out, "/// Identifies a metric defined in the schema.").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(out, "#[repr(u16)]").unwrap();
    writeln!(out, "pub enum MetricId {{").unwrap();
    for (i, fm) in flat.iter().enumerate() {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        writeln!(out, "    /// {}", fm.metric.description).unwrap();
        writeln!(out, "    {vname} = {i},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl MetricId {{").unwrap();

    // name() — returns just the metric name, not namespace-prefixed
    writeln!(out, "    /// Returns the metric name as defined in the schema (without namespace).").unwrap();
    writeln!(out, "    pub fn name(&self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for fm in &flat {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        writeln!(out, "            MetricId::{vname} => \"{}\",", fm.metric.name).unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // namespace() — returns the namespace segments as a static slice
    writeln!(out, "    /// Returns the namespace path for this metric as a static slice of segments.").unwrap();
    writeln!(out, "    pub fn namespace(&self) -> &'static [&'static str] {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for fm in &flat {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        if fm.namespace.is_empty() {
            writeln!(out, "            MetricId::{vname} => &[],").unwrap();
        } else {
            let segments: Vec<String> = fm.namespace.iter().map(|s| format!("\"{s}\"")).collect();
            writeln!(out, "            MetricId::{vname} => &[{}],", segments.join(", ")).unwrap();
        }
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // metric_type()
    writeln!(out, "    /// Returns the aggregation type for this metric.").unwrap();
    writeln!(out, "    pub fn metric_type(&self) -> MetricType {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for fm in &flat {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        let mt = match fm.metric.metric_type {
            MetricType::Count => "MetricType::Count",
            MetricType::Gauge => "MetricType::Gauge",
            MetricType::Histogram => "MetricType::Histogram",
        };
        writeln!(out, "            MetricId::{vname} => {mt},").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // description()
    writeln!(out, "    /// Returns the human-readable description of this metric.").unwrap();
    writeln!(out, "    pub fn description(&self) -> &'static str {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for fm in &flat {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        let desc = fm.metric.description.replace('"', "\\\"");
        writeln!(out, "            MetricId::{vname} => \"{desc}\",").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Display
    writeln!(out, "impl fmt::Display for MetricId {{").unwrap();
    writeln!(out, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{").unwrap();
    writeln!(out, "        f.write_str(self.name())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ALL_METRICS
    writeln!(out, "/// All metric IDs defined in the schema, in definition order.").unwrap();
    writeln!(
        out,
        "pub const ALL_METRICS: &[MetricId] = &[{}];",
        flat.iter()
            .map(|fm| format!("MetricId::{}", variant_name(&fm.namespace, &fm.metric.name)))
            .collect::<Vec<_>>()
            .join(", ")
    ).unwrap();
    writeln!(out).unwrap();
}

fn generate_metric_tags_structs(out: &mut String, schema: &MetricsSchema) {
    let flat = schema.flatten_metrics();

    for fm in &flat {
        let vname = variant_name(&fm.namespace, &fm.metric.name);
        let struct_name = format!("{vname}Tags");

        let qualified = if fm.namespace.is_empty() {
            fm.metric.name.clone()
        } else {
            format!("{}::{}", fm.namespace.join("::"), fm.metric.name)
        };

        writeln!(out, "/// Tag set for the `{qualified}` metric.").unwrap();
        writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]").unwrap();
        writeln!(out, "pub struct {struct_name} {{").unwrap();

        for tag_ref in &fm.metric.tags {
            let field_name = tag_ref
                .export_name
                .as_ref()
                .map(|n| to_snake_case(n))
                .unwrap_or_else(|| to_snake_case(&tag_ref.tag));
            let type_name = to_pascal_case(&tag_ref.tag);

            if tag_ref.optional {
                writeln!(out, "    pub {field_name}: Option<{type_name}>,").unwrap();
            } else {
                writeln!(out, "    pub {field_name}: {type_name},").unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Hash impl
        writeln!(out, "impl Hash for {struct_name} {{").unwrap();
        if fm.metric.tags.is_empty() {
            writeln!(out, "    fn hash<H: Hasher>(&self, _state: &mut H) {{").unwrap();
        } else {
            writeln!(out, "    fn hash<H: Hasher>(&self, state: &mut H) {{").unwrap();
        }
        for tag_ref in &fm.metric.tags {
            let field_name = tag_ref
                .export_name
                .as_ref()
                .map(|n| to_snake_case(n))
                .unwrap_or_else(|| to_snake_case(&tag_ref.tag));
            writeln!(out, "        self.{field_name}.hash(state);").unwrap();
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // export_pairs()
        writeln!(out, "impl {struct_name} {{").unwrap();
        writeln!(out, "    /// Returns `(export_name, value)` pairs for all set tags.").unwrap();
        writeln!(out, "    pub fn export_pairs(&self) -> Vec<(&'static str, String)> {{").unwrap();
        if fm.metric.tags.is_empty() {
            writeln!(out, "        Vec::new()").unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
            continue;
        }
        writeln!(out, "        let mut pairs = Vec::new();").unwrap();

        for tag_ref in &fm.metric.tags {
            let tag_def = &schema.tags[&tag_ref.tag];
            let export_name = tag_ref
                .export_name
                .as_deref()
                .unwrap_or(&tag_def.export_name);
            let field_name = tag_ref
                .export_name
                .as_ref()
                .map(|n| to_snake_case(n))
                .unwrap_or_else(|| to_snake_case(&tag_ref.tag));

            if tag_ref.optional {
                writeln!(out, "        if let Some(ref v) = self.{field_name} {{").unwrap();
                writeln!(out, "            pairs.push((\"{export_name}\", v.to_string()));").unwrap();
                writeln!(out, "        }}").unwrap();
            } else {
                writeln!(out, "        pairs.push((\"{export_name}\", self.{field_name}.to_string()));").unwrap();
            }
        }

        writeln!(out, "        pairs").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}
