use super::schema::{MetricType, MetricsSchema, TagValueType};

use std::fmt::Write;
use std::path::Path;

/// Generate Rust source code from a metrics JSON schema file.
///
/// This function is intended to be called from an **external crate's** `build.rs`.
/// It generates code that references `chalk_metrics::client::*`.
///
/// # Usage in `build.rs`
///
/// ```rust,ignore
/// fn main() {
///     chalk_metrics::codegen::generate("metrics.json");
/// }
/// ```
///
/// Then in your library code:
///
/// ```rust,ignore
/// mod metrics {
///     include!(concat!(env!("OUT_DIR"), "/metrics_generated.rs"));
/// }
/// ```
#[allow(dead_code)] // Used by external crates; build.rs uses generate_with_crate_path directly
pub fn generate(schema_path: impl AsRef<Path>) {
    generate_with_crate_path(schema_path, "chalk_metrics");
}

/// Generate code with a custom crate path. Use `"crate"` when calling from
/// the chalk-metrics crate's own build.rs.
pub fn generate_with_crate_path(schema_path: impl AsRef<Path>, crate_path: &str) {
    let schema_path = schema_path.as_ref();
    let json = std::fs::read_to_string(schema_path).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to read schema file '{}': {e}",
            schema_path.display()
        )
    });

    let schema = MetricsSchema::from_json(&json).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to parse schema '{}': {e}",
            schema_path.display()
        )
    });

    schema.validate().unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: schema validation failed for '{}':\n{e}",
            schema_path.display()
        )
    });

    let code = generate_code(&schema, crate_path);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set (must be run from build.rs)");
    let out_path = Path::new(&out_dir).join("metrics_generated.rs");
    std::fs::write(&out_path, code).unwrap_or_else(|e| {
        panic!(
            "chalk-metrics codegen: failed to write '{}': {e}",
            out_path.display()
        )
    });

    println!("cargo:rerun-if-changed={}", schema_path.display());
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let mut out = c.to_uppercase().to_string();
                    out.extend(chars);
                    out
                }
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

/// Build a PascalCase name from namespace path + metric name.
fn variant_name(namespace: &[String], metric_name: &str) -> String {
    let mut name = String::new();
    for ns in namespace {
        name.push_str(&to_pascal_case(ns));
    }
    name.push_str(&to_pascal_case(metric_name));
    name
}

fn generate_code(schema: &MetricsSchema, crate_path: &str) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "// Generated by chalk-metrics codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use std::fmt;").unwrap();
    writeln!(out, "use std::hash::{{Hash, Hasher}};").unwrap();
    writeln!(out).unwrap();

    generate_tag_types(&mut out, schema);
    generate_metric_structs(&mut out, schema, crate_path);

    out
}

fn generate_tag_types(out: &mut String, schema: &MetricsSchema) {
    let mut tag_names: Vec<&String> = schema.tags.keys().collect();
    tag_names.sort();

    for tag_name in &tag_names {
        let tag_def = &schema.tags[*tag_name];
        let type_name = to_pascal_case(tag_name);

        match tag_def.value_type {
            TagValueType::Enum => {
                let values = tag_def.values.as_ref().unwrap();
                writeln!(out, "/// Tag values for `{tag_name}` (exported as `{}`).", tag_def.export_name).unwrap();
                writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
                writeln!(out, "pub enum {type_name} {{").unwrap();
                for value in values {
                    writeln!(out, "    {},", to_pascal_case(value)).unwrap();
                }
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl {type_name} {{").unwrap();
                writeln!(out, "    pub fn as_str(&self) -> &'static str {{").unwrap();
                writeln!(out, "        match self {{").unwrap();
                for value in values {
                    writeln!(out, "            {type_name}::{} => \"{value}\",", to_pascal_case(value)).unwrap();
                }
                writeln!(out, "        }}").unwrap();
                writeln!(out, "    }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();

                writeln!(out, "impl fmt::Display for {type_name} {{").unwrap();
                writeln!(out, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{ f.write_str(self.as_str()) }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
            }
            TagValueType::String => {
                writeln!(out, "/// Tag values for `{tag_name}` (exported as `{}`). Accepts arbitrary strings.", tag_def.export_name).unwrap();
                writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq, Hash)]").unwrap();
                writeln!(out, "pub struct {type_name}(pub String);").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "impl {type_name} {{ pub fn as_str(&self) -> &str {{ &self.0 }} }}").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "impl fmt::Display for {type_name} {{").unwrap();
                writeln!(out, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{ f.write_str(&self.0) }}").unwrap();
                writeln!(out, "}}").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "impl From<&str> for {type_name} {{ fn from(s: &str) -> Self {{ {type_name}(s.to_owned()) }} }}").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "impl From<String> for {type_name} {{ fn from(s: String) -> Self {{ {type_name}(s) }} }}").unwrap();
                writeln!(out).unwrap();
            }
        }
    }
}

fn generate_metric_structs(out: &mut String, schema: &MetricsSchema, crate_path: &str) {
    let flat = schema.flatten_metrics();

    for fm in &flat {
        let struct_name = variant_name(&fm.namespace, &fm.metric.name);

        let metric_type_str = match fm.metric.metric_type {
            MetricType::Count => "count",
            MetricType::Gauge => "gauge",
            MetricType::Histogram => "histogram",
        };

        // Doc comment
        if fm.namespace.is_empty() {
            writeln!(out, "/// {} ({metric_type_str})", fm.metric.description).unwrap();
        } else {
            let ns_display = fm.namespace.join("::");
            writeln!(
                out,
                "/// {} ({metric_type_str}, namespace: {ns_display})",
                fm.metric.description,
            )
            .unwrap();
        }

        writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]").unwrap();
        writeln!(out, "pub struct {struct_name} {{").unwrap();

        // Fields — use export_name for field names
        for tag_ref in &fm.metric.tags {
            let tag_def = &schema.tags[&tag_ref.tag];
            let field_name = to_snake_case(
                tag_ref
                    .export_name
                    .as_deref()
                    .unwrap_or(&tag_def.export_name),
            );
            let type_name = to_pascal_case(&tag_ref.tag);

            if tag_ref.optional {
                writeln!(out, "    pub {field_name}: Option<{type_name}>,").unwrap();
            } else {
                writeln!(out, "    pub {field_name}: {type_name},").unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Hash impl
        writeln!(out, "impl Hash for {struct_name} {{").unwrap();
        if fm.metric.tags.is_empty() {
            writeln!(out, "    fn hash<H: Hasher>(&self, _state: &mut H) {{}}").unwrap();
        } else {
            writeln!(out, "    fn hash<H: Hasher>(&self, state: &mut H) {{").unwrap();
            for tag_ref in &fm.metric.tags {
                let tag_def = &schema.tags[&tag_ref.tag];
                let field_name = to_snake_case(
                    tag_ref
                        .export_name
                        .as_deref()
                        .unwrap_or(&tag_def.export_name),
                );
                writeln!(out, "        self.{field_name}.hash(state);").unwrap();
            }
            writeln!(out, "    }}").unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // impl block with consts, export_pairs, and record
        writeln!(out, "impl {struct_name} {{").unwrap();

        // Associated consts
        writeln!(out, "    /// The metric name (without namespace).").unwrap();
        writeln!(out, "    pub const NAME: &'static str = \"{}\";", fm.metric.name).unwrap();

        if fm.namespace.is_empty() {
            writeln!(out, "    /// The namespace path (empty for top-level metrics).").unwrap();
            writeln!(out, "    pub const NAMESPACE: &'static [&'static str] = &[];").unwrap();
        } else {
            let segments: Vec<String> = fm.namespace.iter().map(|s| format!("\"{s}\"")).collect();
            writeln!(out, "    /// The namespace path for this metric.").unwrap();
            writeln!(out, "    pub const NAMESPACE: &'static [&'static str] = &[{}];", segments.join(", ")).unwrap();
        }
        writeln!(out).unwrap();

        // export_pairs()
        writeln!(out, "    /// Returns `(export_name, value)` pairs for all set tags.").unwrap();
        writeln!(out, "    pub fn export_pairs(&self) -> Vec<(&'static str, String)> {{").unwrap();
        if fm.metric.tags.is_empty() {
            writeln!(out, "        Vec::new()").unwrap();
            writeln!(out, "    }}").unwrap();
        } else {
            writeln!(out, "        let mut pairs = Vec::new();").unwrap();
            for tag_ref in &fm.metric.tags {
                let tag_def = &schema.tags[&tag_ref.tag];
                let export_name = tag_ref
                    .export_name
                    .as_deref()
                    .unwrap_or(&tag_def.export_name);
                let field_name = to_snake_case(
                    tag_ref
                        .export_name
                        .as_deref()
                        .unwrap_or(&tag_def.export_name),
                );

                if tag_ref.optional {
                    writeln!(out, "        if let Some(ref v) = self.{field_name} {{").unwrap();
                    writeln!(out, "            pairs.push((\"{export_name}\", v.to_string()));").unwrap();
                    writeln!(out, "        }}").unwrap();
                } else {
                    writeln!(out, "        pairs.push((\"{export_name}\", self.{field_name}.to_string()));").unwrap();
                }
            }
            writeln!(out, "        pairs").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        writeln!(out).unwrap();

        // record() method — type depends on metric type
        let hash_code = "        let hash = {\n            use ::std::hash::{Hash, Hasher};\n            let mut hasher = ::std::collections::hash_map::DefaultHasher::new();\n            self.hash(&mut hasher);\n            hasher.finish()\n        };";

        match fm.metric.metric_type {
            MetricType::Count => {
                writeln!(out, "    /// Record a count increment of 1.").unwrap();
                writeln!(out, "    pub fn record(&self) {{ self.record_value(1); }}").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "    /// Record a count delta.").unwrap();
                writeln!(out, "    pub fn record_value(&self, value: i64) {{").unwrap();
                writeln!(out, "{hash_code}").unwrap();
                writeln!(out, "        {crate_path}::client::record_count(Self::NAME, Self::NAMESPACE, hash, || self.export_pairs(), value);").unwrap();
                writeln!(out, "    }}").unwrap();
            }
            MetricType::Gauge => {
                writeln!(out, "    /// Record a gauge value.").unwrap();
                writeln!(out, "    pub fn record(&self, value: f64) {{").unwrap();
                writeln!(out, "{hash_code}").unwrap();
                writeln!(out, "        {crate_path}::client::record_gauge(Self::NAME, Self::NAMESPACE, hash, || self.export_pairs(), value);").unwrap();
                writeln!(out, "    }}").unwrap();
            }
            MetricType::Histogram => {
                writeln!(out, "    /// Record a histogram observation.").unwrap();
                writeln!(out, "    pub fn record(&self, value: f64) {{").unwrap();
                writeln!(out, "{hash_code}").unwrap();
                writeln!(out, "        {crate_path}::client::record_histogram(Self::NAME, Self::NAMESPACE, hash, || self.export_pairs(), value);").unwrap();
                writeln!(out, "    }}").unwrap();
            }
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}
