use std::borrow::Cow;

/// Support trait implemented by tag types generated by `define_tags!`.
#[doc(hidden)]
pub trait MetricTag {
    const EXPORT_NAME: &'static str;

    fn export_value(&self) -> Cow<'static, str>;
}

/// Support trait implemented by namespace marker types generated by
/// `define_namespaces!`.
#[doc(hidden)]
pub trait MetricNamespace {
    fn path() -> &'static [&'static str];
}

/// Marker namespace used for top-level metrics.
#[doc(hidden)]
pub struct NoNamespace;

impl MetricNamespace for NoNamespace {
    #[inline]
    fn path() -> &'static [&'static str] {
        &[]
    }
}
